version: "3.8"

services:
  backend:
    build:
      dockerfile: Dockerfile
      network: host
    container_name: auth_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ${BACKUP_PATH}:/app/backups
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  postgres:
    image: postgres:17
    container_name: auth_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - "5432:5432"
    command: postgres -c 'listen_addresses=*'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
